version: '2'
services:
  db:
    container_name: customerservice-db
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-datavolume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  php:
    container_name: customerservice-php
    build: .
    ports:
      - "8006:80"
      - "442:443"
    volumes:
      - ./:/var/www/html
    links:
    - db

  phpmyadmin:
    container_name: customerservice-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8184:80
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    links:
    - db
volumes:
  mysql-datavolume: