version: '2'
services:
  db:
    container_name: userservice-db
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql-datavolume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  php:
    container_name: userservice-php
    build: .
    ports:
      - "8005:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
    links:
    - db

  phpmyadmin:
    container_name: userservice-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8183:80
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    links:
    - db
volumes:
  mysql-datavolume: